### ISSUE TITLE
Help me please!! -- Error: Can't get personStatus{statusCode=NETWORK_ERROR,resolution=null})

### ISSUE THREAD

**Issue by FranciscoJavierPRamos** [gorbin/ASNE#90]

**Comment by kysmet** [comment]
I am getting the same error too. But, g+ sign in is working on the demo app that I installed from play store.

**Comment by mifa** [comment]
Same here.

**Comment by mifa** [comment]
Fixed by enabling Google Plus in developer console.

**Comment by goyalrahul31** [comment]
how to get this error resolved plz do explain it step by step

**Comment by fantasy1022** [comment]
I meet the same problem. Later, I open google developer console to check signed certificate fingerprint and package name. Whether these info matches your developer APP or not.

**Comment by nikil07** [comment]
I faced the same issue for the tutorial app. 
Create a new google API project, add google+ API. 
Provide the SHA1 and package. 

It will work.

**Comment by phabiulla** [comment]
Error trying to sign in with accounts that have already given permission to the app. Until last week it worked .. I already created a credential in the developer panel as suggested in another topic, but it did not solve.

Has anyone found a solution?
